### PR TITLE
Django 4.0 support

### PR DESCRIPTION
**Pull request by mrg29**
This adds Django 3.2 and Django 4.0, while dropping everything older.

I also cleaned up some dead code.

### CODE REVIEW

**Review by bruth — APPROVED** [review]

**Comment by bruth** [comment]
I have not used Django for years, so I really appreciate this update. For how long it has been, I am surprised (and delighted) with how straightforward the upgrade was.

**Comment by johanneswilm** [comment]
@bruth Ping! Are you going to merge this? If not, would you want to publish this as django-tracking3 @mrg29 ?

**Comment by eyk107** [comment]
@bruth Could you please merge this request? Thank you in advance

**Comment by bruth** [comment]
Sorry for the delay, I am not sure why I didn't do it at the time! I will cut a release later today.

**Comment by eyk107** [comment]
@bruth Thank you very much for the help and thank you for the new release in advance

**Pull request merged**
