### PR TITLE
Django 1.8, 1.9, 1.10, 1.11 testing

### PR DESCRIPTION
**Pull request by mjschultz**
This moves the testing matrix to be up-to-date with [Django's supported versions](https://www.djangoproject.com/download/#supported-versions). It only tests the supported version against the [Python version supported](https://docs.djangoproject.com/en/1.11/faq/install/#what-python-version-can-i-use-with-django) which is getting kind of ugly, but it is what it is.

I've jumped through some hoops to avoid deprecation warnings in the latest Django (i.e. 2.0 ready) while still supporting Django 1.8.

### CODE REVIEW

**Comment by bruth** [comment]
@mjschultz Wow! This is wonderful, thank you for all the work. I just sent you an invite for push access to this repo. You've contributed much more to this project than I over the past couple years.

**Comment by bruth** [comment]
I released 0.4.0 on PyPI.

**Comment by mjschultz** [comment]
Cool, thanks! Would it be possible to give me push access on the pypi repo as well? I think the url is https://pypi.python.org/pypi?:action=role_form&package_name=django-tracking2 and my user name over there is `Michael.Schultz`.

**Comment by bruth** [comment]
Of course! Done.

**Pull request merged**
